---
pagetitle: "projects"
---


### ICM Philly projects

* <a href="https://pjirisk.shinyapps.io/pji_calc/" target="_blank">PJI Risk Calculator</a>
  * Calculates the risk of periprosthetic joint infection after total joint arthroplasty using a regression model

* <a href="https://pjirisk.shinyapps.io/pjidx/" target="_blank">PJIDx</a>
  * Determines liklihood that patient has an infection using the algorithm developed by ICM

* <a href="https://pjirisk.shinyapps.io/vte_risk_calculator/" target=_"blank">VTE Risk Calculator</a> <i>(in development)</i>
  * Calculates risk of venous thromboembolism, deep vein thrombosis, and/or major bleeding event after TJA using lasso regression (glmnet library) and eXtreme gradient boosting (xgboost library)

* <a href="https://pjirisk.shinyapps.io/DAIR_Calculator/" target=_"blank">DAIR Success Calculator</a>
  * Calculate probability of successfully treating PJI with debridement and implant retention (DAIR) using a random forest model


### Projects for fun

* <a href="https://knicholsonphd.shinyapps.io/spine_pubs/" target="_blank">Recent publications (spine surgery-related)</a>
  * View abstracts from recently published manuscripts covering topics in spine surgery using the PubMed API

* <a href="https://knicholsonphd.shinyapps.io/confidence_intervals/" target="_blank">Sample size visualization</a>
  * Explore the effect of sample size on estimating population mean using D3

* <a href="https://knicholsonphd.shinyapps.io/mesh_api/" target="_blank">MeSH explorer</a>
  * Explore the Medical Subjects Headings (MeSH) from PubMed

* <a href="./files/datahack2020_video_sm.mp4">2020 Opioid Data Hackathon hosted by Code for Philly, DataPhilly and R-Ladies Philly</a> (video)
  * Heatmap and zipcode level maps of drug-related arrests in Philadelphia using data from OpenDataPhilly over time

* <a href="./files/HSX_video.mp4">HSX Hackathon 2019</a> (video)
  * Video overview of app developed for a patient-facing healthcare mobile app
  * App was presented alongside a business plan to an audience comprising of healthcare executives
  * Developed app and business plan over the course of four days with three teammates
  * Won first place, based on business plan, app, and presentation